### ISSUE TITLE
Error loading entity NBT

### ISSUE THREAD

**Issue by guillaumearm** [ben-mkiv/OpenEntity#1]
```
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1875) ~[vg.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:224) ~[bfb.class:?]
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:323) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:116) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
	at ben_mkiv.openentity.network.OpenEntityNetwork.sendToTrackingPlayers(OpenEntityNetwork.java:47) ~[OpenEntityNetwork.class:?]
	at ben_mkiv.openentity.common.capability.capabilities.syncToClients(capabilities.java:72) ~[capabilities.class:?]
	at ben_mkiv.openentity.common.capability.customInventory.customInventoryProvider.readFromNBT(customInventoryProvider.java:234) ~[customInventoryProvider.class:?]
	at ben_mkiv.openentity.common.capability.customInventory.customInventoryStorage.readNBT(customInventoryStorage.java:11) ~[customInventoryStorage.class:?]
	at ben_mkiv.openentity.common.capability.customInventory.customInventoryStorage.readNBT(customInventoryStorage.java:8) ~[customInventoryStorage.class:?]
	at ben_mkiv.openentity.common.capability.customInventory.customInventoryCapability.deserializeNBT(customInventoryCapability.java:53) ~[customInventoryCapability.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:135) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1849) ~[vg.class:?]
	... 13 more
```

I cannot connect to my server because this error.

Here is my ForgeCaps NBT data for my player
![image](https://user-images.githubusercontent.com/16897658/40754301-e483ec98-6478-11e8-8d5b-ab1c2c47ae15.png)

**EDIT**: I use [OpenEntity 1.0.0-alpha_V15 for minecraft 1.12.2](https://minecraft.curseforge.com/projects/openentity/files/2564064)

Please note the problem appear when I disconnect from the end (dimension 1)

**Comment by ben-mkiv** [comment]
Thanks for the report, i've hopefully(!) fixed the bug and uploaded a new snapshot to curse which should fix the problem :)

https://minecraft.curseforge.com/projects/openentity/files/2567794

**Comment by guillaumearm** [comment]
I just tried this new snapshot on my server and it works perfectly, good job 👍 

A little question, can I find somewhere the OpenEntity sources ?

**Comment by ben-mkiv** [comment]
not yet, but i might release it once the core features are done
